apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>ConfigMap Page</title>
    </head>
    <body>
      <h1>Эта страница загруженав из ConfigMap Kubernetes!</h1>
    </body>
    </html>
